jobs:
  include:
    - language: python
      python:
        - "3.6"
        - "3.7"
        - "3.8"
      before_install:
        - cd backend
      install:
        - pip install pipenv
        - pipenv install --dev
      script:
        - pytest ./tests/
    - language: node_js
      node_js:
        - "14.3.0"
      before_install:
        - cd frontend
      install:
        - npm install --dev
      script:
        - npm run build
        - npm run headless-test
