language: python
python:
- 3.8.5
install:
- pip install pipenv
stages:
- tests
- deploy
env:
  global:
  - PIPENV_IGNORE_VIRTUALENVS=1
jobs:
  include:
  - stage: tests
    script:
    - pipenv sync --dev
    - pytest ./tests/
    - echo 'Dependencies installed:'
    - cat Pipfile.lock
    - cat requirements.txt
  - stage: deploy
    script:
    - pipenv lock --clear
    - pipenv sync
    - pipenv lock -r > requirements.txt
    - echo 'Dependencies installed:'
    - cat Pipfile.lock
    - cat requirements.txt
    deploy:
      provider: heroku
      api_key:
        secure: KnOPTbxDAHEwW/Ij7zLXSjPSIhbseogeLfDRVEerRQIsChQv//kYhDlV4VTPmWf/d60iyVDuyO8zYrWrq130nx3bZSLSdFQ/VYNrCC0ZfuNVgT56JuyCezKrRvQCxFZrdZwTKryVcwYeC+iaBNaBFmPze/Pe8jlMgFf5O+VHpnWxDVRoN6Q3aQuGP167FC6BAneufJFxTDd9Buh1IzNlAYZN5hEJrFy6Fio9CHXHnb+1sQnYp0ZsxPlEgBSQHxpWmyyMDRiuHUZ88W0oy0qTDz72B8k4b24vlwHbL+C1tKY522W83l33QnUaea8RxvUI21h0rbsVP5GYTq/ihHdAhgV1UIHWd/B0C8/tM6t6XuCQvyVX8XbezsssEw+h34BjeJNiMLNrPnOOFGFvRRbsYt/kmX/TrUuKB7njorFxcbT9gdZzWSssM7EtA+zgBjcslgxZdYf8cLXYpUESU1sCypuVu1vNQCeVsh7OiOlhGAYgncGyus2hXlKgQy+WuBFra2KgmKj5tO75ueLCU3nbKq+N/resedVosEyu9CV08UuaAbA6q0ZqcNON/ExohFzPTDP/7KJSjMllUz58o2wOoz353wvkcpLP+stZx4ro0XJ0/vhTT3xg9urfmeiq92RdNGgfoNxw6cEiqK4xwDOMzoq7prCr06NO3l3cIz5heVM=
      app: the-recommender-heroku
      skip_cleanup: true
